version: '3'
services:
  backend:
    image: ${DOCKER_BACK_REPO}/${DOCKER_BACK_TAG}
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_ACCESS_TOKEN_TIME=${JWT_ACCESS_TOKEN_TIME}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
    expose:
      - 3000
  redis:
    image: 'redis:6.0.9-alpine'
    expose:
      - 6379
  
  frontend:
    image: ${DOCKER_REPO}:latest
    ports:
      - 80:80
      - 443:443

    volumes:
    - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
    - /etc/letsencrypt/live/www.lockfestival.com/fullchain.pem:/etc/ssl/cert.pem
    - /etc/letsencrypt/live/www.lockfestival.com/privkey.pem:/etc/ssl/key.pem