import { GroupInfoCardProps } from 'types/recruitment';

export const recruitmentCardMock: Array<GroupInfoCardProps> = [
  {
    leader: {
      nickname: '정민쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CHASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 1,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민89쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CHA09-SER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 31,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민56쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CH56ASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 71,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민12쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CH23ASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 81,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민쓰z',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CHASEgR - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 1231,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민쓰v',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CHASrER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 7681,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정c민쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOULz CHASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 21,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민b쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUbL CHASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 14567,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정m민쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CHASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 675671,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민6쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CHASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 581,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정2민쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SO2UL CHASER - 실종',
      realGenre: '야외5',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 111,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정민3쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL 23CHASER - 실종',
      realGenre: '3야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 1222,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정7민쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL C0-HASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 133,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정56민쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL99 CHASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 144,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '정567민5쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CH567ASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 188,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
  {
    leader: {
      nickname: '32정민쓰',
      profileImageUrl: '',
    },
    themeDetail: {
      themeName: 'SOUL CHASER - 실종',
      realGenre: '야외',
      themeId: 1,
      posterImageUrl: 'https://i.postimg.cc/nLwL9k0H/theme-SOUL-CHASER.jpg',
      difficulty: 4,
      minMember: 2,
      maxMember: 2,
      playTime: 90,
      phone: '02-463-9967',
      address: '서울특별시 광진구 자양동 17-5 B1',
      website: 'https://www.nextedition.co.kr/shops/NextEdition%20Gundae',
      branchName: '넥스트에디션',
    },
    groupDetail: {
      groupId: 19568,
      appointmentDate: new Date('2023-11-28T09:39:44.928Z'),
      appointmentTime: new Date('2023-11-28T09:39:44.928Z'),
      currentMembers: 2,
      recruitmentMembers: 4,
      recruitmentCompleted: false,
      appointmentCompleted: false,
      recruitmentContent: '(테마 변경 가능)11월 5일 오후 5시에 갈사람 구해요.',
      hasPassword: false,
      isEnter: false,
    },
  },
];
