version: '3'
services:
  web:
    image: ${DOCKER_BACK_REPO}/${DOCKER_BACK_TAG}
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_ACCESS_TOKEN_TIME=${JWT_ACCESS_TOKEN_TIME}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
  redis:
    image: 'redis:6.0.9-alpine'
    ports:
      - '6379:6379'
